server:
  port: 8099


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chat?serverTimezone=Asia/Shanghai&userSSL=true&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 131452
    driver-class-name: com.mysql.cj.jdbc.Driver